# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YRa4V4Oxv0r8IfxhMuDJf76N8tAT-pFp
"""

import requests

def display_welcome():
    print("=== Welcome to the Conversational Retrieval System ===")
    print("This script interacts with a Flask API for contextual answers.")
    print("Enter your query, and the system will provide a response.")
    print("Type 'exit' to quit.\n")

def chat_loop():
    api_url = "http://localhost:5000/ask"

    while True:
        user_input = input("You: ")
        if user_input.lower() in ["exit", "quit"]:
            print("Goodbye!")
            break

        payload = {"user_input": user_input}

        try:
            response = requests.post(api_url, json=payload)

            if response.status_code == 200:
                print("\nBot:", response.json().get("response", "[No response]"))
            else:
                print(f"Error {response.status_code}: {response.text}")

        except requests.exceptions.RequestException as e:
            print(f"Request failed: {e}")

if __name__ == '__main__':
    display_welcome()
    chat_loop()